# Deploy the web application
# into the vercel as production
#
# ***** NOTE ******
# This deployment need to setup some secrets

name: Web Production

# define the env for this workflows
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_WEB_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID }}

# Oonly run this workflows if
# the user start manual the actions
# and push the code into the main branch
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  update:
    name: Update Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Vercel CLI
        run: bun add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
